= Rust on STM32 Notebook

用 Rust 编写 STM32F411RET6 程序的笔记

== 常见问题

Q00: 就学习 STM32F411RET6 最重要的文档是哪些

A00: 最重要的莫过于

1. STM32F411RET6 的 Datasheet，里面包含了 Block Diagram、引脚定义、GPIO 功能表、内存映射关系 等等编程需要知道的信息，以及各种 电气特性 等等硬件设计需要知道的信息。

2. STM32F411RET6 的 Reference Manual，里面包含了详尽的 设备功能与使用方法，以及对应的寄存器配置 的信息、


Q01: 向 STM32F411RET6 **刷写** 程序需要编程器（Flasher）/排错器（Debugger，比如 STLink/JLink/CMSIS-DAP/DAPLink）么？

A01: 理论上不需要，当我们修改 BOOT PIN 至 1 后，会从芯片的 System Memory（是一段 ROM）启动，该程序会启动 USART, USB OTG FS, DFU, I2C, SPI， +
然后它们各自会监听特殊的信号，然后再进入刷写阶段，（见 ST 文档 AN2606、AN3155、AN3156、AN4286）
因此，实际上我们只需要一个串口转 USB 的设备，连接好 USART 端口，然后用特定的软件（比如 FLASHER-STM32/STM32CubeProg），就可以刷写程序到板子上了

Q02: 所以排错器是不重要的？

A02: 非也，相反，排错器非常重要，毕竟我们是写程序，那么控制 STM32F411RET6 的运行的能力，比如 随时中断程序的运行、查看内存的情况的功能则非常的重要 +
这些只能靠 Debugger 实现。

Q03: 串口是 Debug 口么？

A03: 串口不是 STM32F411RET6 原生的 Debug 口，有这种误解是因为，我们经常使用**已经写好程序**的微控制器，而**那些程序**会启动串口打印一些信息。+
STM32F411RET6 硬件定义的 Debug 接口就两种 JTAG 和 SW

== 一些基础概念

Cortex-M4

一颗处理器（等同于 CPU），上面有一颗处理器所必要的电路， +
准确来说是 ARM 公司提供的一颗处理器的电路设计稿，而实际生产“这颗处理器”的厂家可以微微修改一些部分

上面的“这颗处理器”打了引号，这是由于仅仅制造一颗处理器，那么这颗处理器啥事也做不了，它缺少一些关键的部件， 比如： +
电源（用来供电）、时钟（用来同步电路来运行）、一些必要的外部设备（用来接收数据以及发送数据）

STM32F411RET6

购买了 ARM 提供的“图纸”的厂家（比如 STMicroelectronics）不仅会制造处理器，还会一同把周边的所需的电路一同设计和制造出来。 +
而且，由于制造出来的芯片已经包含了 处理器、电源、时钟、基本 IO 等等功能，是一个较为完整的系统，且它们还都封装在一个芯片里， +
这种芯片又称为 片上系统（System on Chip），英文简称 SoC。

我们手上的 STM32F411RET6 就是这颗 SoC 的名称，就是那个在电路板上黑色的大方块，上面会写着 STM32F411RET6 的字样

开发板 / 最小板 / 核心板

而要让这颗 SoC 成功启动，并与我们现有的其它系统交互，它还需要一些简单的外部电路， +
这部分电路就可以交由我们自己设计制造，或者交由 开发板/核心板 制造商制造， +
最后我们大概率会获得一个块带着 SoC，有一些外周电路，并可能具有 Micro USB 口的 电路板

ARMv7E-M

是 Cortex-M4 处理器所属的指令集架构，同属该架构的处理器还有 Cortex-M7 +
这个指令集架构实际上是 ARMv7-M 的一个扩展架构，前者比后者多了 DSP 相关的指令和电路

thumbv7em

Cortex-M4 所使用的指令集的名称， +
该名称可以简单拆解为两个部分 thumb 和 v7em，前者是 ARM 推出的用于微控制器的指令集 thumb，后者则直接截取自指令集架构的后三个字母
